[[spring-core]]
= Core Technologies

This part of the reference documentation covers all the technologies that are absolutely integral to the Spring Framework.  +
Core Technologies部分涵盖了Spring框架中绝对不可或缺的所有技术。

Foremost amongst these is the Spring Framework's Inversion of Control (IoC) container.
A thorough treatment of the Spring Framework's IoC container is closely followed by comprehensive coverage of Spring's Aspect-Oriented Programming (AOP) technologies.
The Spring Framework has its own AOP framework, which is conceptually easy to understand and which successfully addresses the 80% sweet spot of AOP requirements in Java enterprise programming.  +
其中最重要的是Spring框架的控制反转（IoC）容器。
在对Spring框架的IoC容器进行详细的讲解之后，紧跟着是对Spring的面向方面编程（AOP）技术的全面介绍。
Spring框架有自己的AOP框架，它在概念上很容易理解，并且成功地解决了Java企业编程中80%的AOP需求。

Coverage of Spring's integration with AspectJ (currently the richest -- in terms of features -- and certainly most mature AOP implementation in the Java enterprise space) is also provided.  +
本文还介绍了Spring与AspectJ的集成（目前是Java企业领域中最丰富的——就特性而言——当然也是最成熟的AOP实现）。

AOT processing can be used to optimize your application ahead-of-time. It is typically used for native image deployment using GraalVM.  +
AOT处理可用于提前优化应用程序。它通常用于使用GraalVM进行本机映像部署。











