[[overview]]
= Spring Framework Overview
:docinfo1:

Spring makes it easy to create Java enterprise applications. It provides everything you need to embrace the Java language in an enterprise environment, with support for Groovy and Kotlin as alternative languages on the JVM, and with the flexibility to create many kinds of architectures depending on an application's needs. As of Spring Framework 6.0, Spring requires Java 17+.  +
Spring使创建Java企业应用程序变得容易。它提供了在企业环境中使用Java语言所需的一切，支持Groovy和Kotlin作为JVM上的替代语言，并具有根据应用程序需求创建多种体系结构的灵活性。从Spring Framework 6.0开始，Spring需要Java 17+。

Spring supports a wide range of application scenarios. In a large enterprise, applications often exist for a long time and have to run on a JDK and application server whose upgrade cycle is beyond the developer's control. Others may run as a single jar with the server embedded,
possibly in a cloud environment. Yet others may be standalone applications (such as batch or integration workloads) that do not need a server.  +
Spring支持广泛的应用场景。在大型企业中，应用程序通常存在很长时间，并且必须在JDK和应用程序服务器上运行，其升级周期超出开发人员的控制范围。其他可能在云环境中作为嵌入服务器的单个jar运行。还有一些可能是不需要服务器的独立应用程序（如批处理或集成工作负载）。

Spring is open source. It has a large and active community that provides continuous feedback based on a diverse range of real-world use cases. This has helped Spring to successfully evolve over a very long time.  +
Spring是开源的。它有一个庞大而活跃的社区，提供基于各种实际用例的持续反馈。这帮助Spring在很长一段时间内成功地发展。




[[overview-spring]]
== What We Mean by "Spring"

The term "Spring" means different things in different contexts. It can be used to refer to the Spring Framework project itself, which is where it all started. Over time, other Spring projects have been built on top of the Spring Framework. Most often, when people say
"Spring", they mean the entire family of projects. This reference documentation focuses on the foundation: the Spring Framework itself.  +
术语“Spring”在不同的上下文中有不同的含义。它可以用来引用Spring框架项目本身，这是它开始的地方。随着时间的推移，其他Spring项目已经构建在Spring框架之上。大多数情况下，当人们说“Spring”，他们指的是整个项目家族。本参考文档主要关注其基础：Spring框架本身。

The Spring Framework is divided into modules. Applications can choose which modules they need.
At the heart are the modules of the core container, including a configuration model and a dependency injection mechanism. Beyond that, the Spring Framework provides foundational support for different application architectures, including messaging, transactional data and persistence, and web. It also includes the Servlet-based Spring MVC web framework and, in parallel, the Spring WebFlux reactive web framework.  +
Spring框架分为几个模块。应用程序可以选择它们需要的模块。
核心容器的模块处于核心位置，包括配置模型和依赖项注入机制。除此之外，Spring框架还为不同的应用程序体系结构提供了基础支持，包括消息传递、事务性数据和持久性以及web。它还包括基于servlet的Spring MVC web框架，以及Spring WebFlux响应式web框架。

A note about modules: Spring Framework's jars allow for deployment to the module path (Java Module System). For use in module-enabled applications, the Spring Framework jars come with `Automatic-Module-Name` manifest entries which define stable language-level module names (`spring.core`, `spring.context`, etc.) independent from jar artifact names. The jars follow the same naming pattern with `-` instead of `.` – for example, `spring-core` and `spring-context`.
Of course, Spring Framework's jars also work fine on the classpath.  +
关于模块的注意事项：Spring框架的jar允许部署到模块路径（Java module System）。为了在支持模块的应用程序中使用，Spring Framework jar附带了 `Automatic-Module-Name` 清单项，它定义了稳定的语言级模块名称（`spring.core`, `spring.context`,等)，独立于jar构件名称。jar遵循相同的命名模式，使用 `-` 而不是 `.`，例如 `spring-core` 和 `spring-context`。当然，Spring Framework的jar在类路径上也能很好地工作。




[[overview-history]]
== History of Spring and the Spring Framework

Spring came into being in 2003 as a response to the complexity of the early
https://en.wikipedia.org/wiki/Java_Platform,_Enterprise_Edition[J2EE] specifications.
While some consider Java EE and its modern-day successor Jakarta EE to be in competition with Spring, they are in fact complementary. The Spring programming model does not embrace the Jakarta EE platform specification; rather, it integrates with carefully selected individual specifications from the traditional EE umbrella:  +
Spring于2003年诞生，作为对早期
https://en.wikipedia.org/wiki/Java_Platform,_Enterprise_Edition[J2EE] 规范复杂性的回应。
虽然有些人认为Java EE及其现代继承者Jakarta EE与Spring是竞争关系，但实际上它们是互补的。Spring编程模型不支持Jakarta EE平台规范；相反，它集成了传统EE保护伞中精心挑选的个人规格：

* Servlet API ({JSR}340[JSR 340])
* WebSocket API ({JSR}356[JSR 356])
* Concurrency Utilities 并发实用程序 ({JSR}236[JSR 236])
* JSON Binding API ({JSR}367[JSR 367])
* Bean Validation ({JSR}303[JSR 303])
* JPA ({JSR}338[JSR 338])
* JMS ({JSR}914[JSR 914])
* as well as JTA/JCA setups for transaction coordination, if necessary. 事务性的JTA/JCA设置

The Spring Framework also supports the Dependency Injection
({JSR}330[JSR 330]) and Common Annotations
({JSR}250[JSR 250]) specifications, which application developers may choose to use instead of the Spring-specific mechanisms provided by the Spring Framework. Originally, those were based on common `javax` packages.  +
Spring框架还支持 Dependency Injection（{JSR}330[JSR 330]）和 Common Annotations（{JSR}250[JSR 250]）规范，应用程序开发人员可以选择使用它来代替Spring框架所提供的Spring特定机制。根源上，它们都基于通用的 `javax` 包。

As of Spring Framework 6.0, Spring has been upgraded to the Jakarta EE 9 level
(for example, Servlet 5.0+, JPA 3.0+), based on the `jakarta` namespace instead of the traditional `javax` packages. With EE 9 as the minimum and EE 10 supported already,
Spring is prepared to provide out-of-the-box support for the further evolution of the Jakarta EE APIs. Spring Framework 6.0 is fully compatible with Tomcat 10.1,
Jetty 11 and Undertow 2.3 as web servers, and also with Hibernate ORM 6.1.  +
从Spring Framework 6.0开始，Spring已经升级到Jakarta EE 9（例如Servlet 5.0+, JPA 3.0+），基于 `jakarta` 命名空间而不是传统的 `javax` 包。以EE 9为最低标准，并且已经支持EE 10，Spring准备为Jakarta EE api的进一步发展提供开箱即用的支持。Spring Framework 6.0与Tomcat 10.1完全兼容，Jetty 11和Undertow 2.3作为web服务器，以及Hibernate ORM 6.1。

Over time, the role of Java/Jakarta EE in application development has evolved. In the early days of J2EE and Spring, applications were created to be deployed to an application server. Today, with the help of Spring Boot, applications are created in a devops- and cloud-friendly way, with the Servlet container embedded and trivial to change. As of Spring Framework 5, a WebFlux application does not even use the Servlet API directly and can run on servers (such as Netty) that are not Servlet containers.  +
随着时间的推移，Java/Jakarta EE在应用程序开发中的角色不断发展。在J2EE和Spring的早期，创建应用程序是为了部署到应用服务器上。如今，在Spring Boot的帮助下，应用程序可以以一种对devops和云友好的方式创建，并嵌入Servlet容器，更改非常简单。从Spring Framework 5开始，WebFlux应用程序甚至不直接使用Servlet API，可以在不是Servlet容器的服务器（比如Netty）上运行。

Spring continues to innovate and to evolve. Beyond the Spring Framework, there are other projects, such as Spring Boot, Spring Security, Spring Data, Spring Cloud, Spring Batch, among others. It’s important to remember that each project has its own source code repository, issue tracker, and release cadence. See {spring-site-projects}[spring.io/projects] for the complete list of Spring projects.  +
Spring继续创新和发展。除了Spring框架，还有其他项目，如Spring Boot、Spring Security、Spring Data、Spring Cloud、Spring Batch等。重要的是要记住，每个项目都有自己的源代码存储库、问题跟踪器和发布节奏。在 {spring-site-projects}[spring.io/projects] 查看Spring项目的完整列表。




[[overview-philosophy]]
== Design Philosophy【设计哲学】

When you learn about a framework, it’s important to know not only what it does but what principles it follows. Here are the guiding principles of the Spring Framework:  +
当您学习一个框架时，重要的是不仅要知道它做什么，还要知道它遵循什么原则。以下是Spring框架的指导原则：

* Provide choice at every level. Spring lets you defer design decisions as late as possible.
For example, you can switch persistence providers through configuration without changing your code. The same is true for many other infrastructure concerns and integration with third-party APIs.  +
在每个层面提供选择。Spring允许您尽可能晚地推迟设计决策。
例如，您可以通过配置切换持久性提供程序，而无需更改代码。对于许多其他基础设施问题和与第三方api的集成也是如此。
* Accommodate diverse perspectives. Spring embraces flexibility and is not opinionated about how things should be done. It supports a wide range of application needs with different perspectives.  +
包容不同的观点。Spring拥抱灵活性，并且不固执于应该如何做事情。它支持具有不同视角的广泛应用程序需求。
* Maintain strong backward compatibility. Spring’s evolution has been carefully managed to force few breaking changes between versions. Spring supports a carefully chosen range of JDK versions and third-party libraries to facilitate maintenance of applications and libraries that depend on Spring.  +
保持强大的向后兼容性。Spring的演变得到了精心的管理，在版本之间很少强制进行突破性的更改。Spring支持一系列精心挑选的JDK版本和第三方库，以方便对依赖Spring的应用程序和库的维护。
* Care about API design. The Spring team puts a lot of thought and time into making APIs that are intuitive and that hold up across many versions and many years.  +
关注API设计。Spring团队投入了大量的精力和时间来制作直观的api，这些api可以跨越许多版本和许多年。
* Set high standards for code quality. The Spring Framework puts a strong emphasis on meaningful, current, and accurate javadoc. It is one of very few projects that can claim clean code structure with  no circular dependencies between packages.  +
为代码质量设定高标准。Spring框架非常强调有意义的、最新的和准确的javadoc。它是少数几个可以宣称代码结构干净且包之间没有循环依赖的项目之一。




[[overview-feedback]]
== Feedback and Contributions【反馈和贡献】

For how-to questions or diagnosing or debugging issues, we suggest using Stack Overflow. Click
{stackoverflow-spring-tag}+or+spring-mvc+or+spring-aop+or+spring-jdbc+or+spring-r2dbc+or+spring-transactions+or+spring-annotations+or+spring-jms+or+spring-el+or+spring-test+or+spring+or+spring-orm+or+spring-jmx+or+spring-cache+or+spring-webflux+or+spring-rsocket?tab=Newest[here]
for a list of the suggested tags to use on Stack Overflow. If you're fairly certain that there is a problem in the Spring Framework or would like to suggest a feature, please use the {spring-framework-issues}[GitHub Issues].  +
对于如何操作问题或诊断或调试问题，我们建议使用Stack Overflow。点击
{stackoverflow-spring-tag}+or+spring-mvc+or+spring-aop+or+spring-jdbc+or+spring-r2dbc+or+spring-transactions+or+spring-annotations+or+spring-jms+or+spring-el+or+spring-test+or+spring+or+spring-orm+or+spring-jmx+or+spring-cache+or+spring-webflux+or+spring-rsocket?tab=Newest[here]
查看在Stack Overflow上使用的建议标签列表。如果您相当确定Spring框架中存在问题或想要建议一个功能，请使用 {spring-framework-issues}[GitHub Issues]。

If you have a solution in mind or a suggested fix, you can submit a pull request on
{spring-framework-github}[Github]. However, please keep in mind that, for all but the most trivial issues, we expect a ticket to be filed in the issue tracker, where discussions take place and leave a record for future reference.  +
如果您有一个解决方案或建议修复，您可以提交 pull request
{spring-framework-github}[Github]。但是，请记住，除了最琐碎的问题之外，我们希望在问题跟踪器中提交一个 ticket，在那里进行讨论并留下记录以供将来参考。

For more details see the guidelines at the {spring-framework-code}/CONTRIBUTING.md[CONTRIBUTING], top-level project page.  +
要了解更多细节，请参阅 {spring-framework-code}/CONTRIBUTING.md[CONTRIBUTING]，顶级项目页面。



[[overview-getting-started]]
== Getting Started

If you are just getting started with Spring, you may want to begin using the Spring Framework by creating a {spring-site-projects}/spring-boot/[Spring Boot]-based application. Spring Boot provides a quick (and opinionated) way to create a production-ready Spring-based application. It is based on the Spring Framework, favors convention over configuration, and is designed to get you up and running as quickly as possible.  +
如果你刚刚开始使用Spring，你可能想通过创建一个基于 {spring-site-projects}/spring-boot/[Spring Boot] 的应用程序来开始使用Spring框架。Spring Boot提供了一种快速（且固执己见）的方法来创建 production-ready 的 Spring-based 的应用程序。它基于Spring框架，支持约定而不是配置，旨在让您尽可能快地启动和运行。

You can use https://start.spring.io/[start.spring.io] to generate a basic project or follow one of the {spring-site-guides}["Getting Started" guides], such as {spring-site-guides}/gs/rest-service/[Getting Started Building a RESTful Web Service].
As well as being easier to digest, these guides are very task focused, and most of them are based on Spring Boot. They also cover other projects from the Spring portfolio that you might want to consider when solving a particular problem.  +
你可以使用 https://start.spring.io/[start.spring.io] 来生成一个基本的项目，或者遵循 {spring-site-guides}[入门指南] 之一，比如 {spring-site-guides}/gs/rest-service/[开始构建RESTful Web服务]。
这些指南不仅易于理解，而且非常注重任务，其中大多数都基于Spring Boot。它们还涵盖了在解决特定问题时可能需要考虑的Spring组合中的其他项目。
